### ISSUE TITLE
CORS policy blocking

### ISSUE THREAD

**Issue by ember-island-engineer** [loocurse/quant-crunch#9]
Hey @leo-dh,

Got the CORS policy problem.

> Access to XMLHttpRequest at 'https://quantcrunch-api.herokuapp.com/api/tickerlist' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

I think the issue can be solved here: https://flask-cors.readthedocs.io/en/latest/

**Comment by leo-dh** [comment]
Ok should be fixed in 7d99d9a38094ebef810fba32c5937a430b53436b.
